# Generated by Django 3.2.12 on 2022-04-07 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, default='story', max_length=256, null=True)),
                ('time', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('upVotes', models.ManyToManyField(related_name='story_upVotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.TextField()),
                ('identifier', models.IntegerField(default=0)),
                ('comment_id', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
